title: Prateekg147
# url: https://bitbrain.github.io
author: Prateek Gianchandani
email: prateek@damnvulnerableiosapp.com
description: > # this means to ignore newlines until "show_exerpts:"
I am Prateek Gianchandani. Currently i am working as a Security Researcher in UAE. 
I have interests in Exploit Development, Mobile and Browser Security. 
I have spoken/trained at Conferences like Blackhat USA, Defcon, Brucon, PHDays, 
Owasp Appsec USA, Hack in Paris, x33fcon etc. <a href="/about">
  Continue</a>
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 20
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  # disqus:
  #   shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
     - url: https://8ksec.io
      icon: company
      color: cyan
    - url: https://twitter.com/prateekg147
      icon: twitter-square
      color: cyan
    - url: https://www.linkedin.com/in/prateekgianchandani/
      icon: linkedin
      color: indigo
    - url: https://github.com/prateek147
      icon: github-square
      color: yellow
      
  avatar_source: local
  avatar_path: https://pbs.twimg.com/profile_images/1244561732170899457/SRr3p2iV_400x400.jpg

# Build settings
theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging


